feat: 🎸 trusted claim issuers: set, add, remove
PolymeshAssociation/polymesh-rest-api pull request #135
Opened 2022-11-04 14:43 UTC by sansan

### JIRA Link 
https://polymesh.atlassian.net/browse/DA-61

### Changelog / Description 

- moves list trusted claim issuers to a separate controller
- Adds endpoints to add, set and remove trusted claim issuers

### Checklist - 

- [x] New Feature ?
- [x] Updated swagger annotation (if API structure is changed) ?
- [x] Unit Test (if possible) ?
- [ ] Updated the Readme.md (if required) ?

2022-11-04 15:49 UTC, polymath-eric reviewed
Can you update this to be against `feature-release` (or `master` if it gets merged)?

2022-11-04 15:49 UTC, polymath-eric commented on src/common/decorators/swagger.ts
> +  messages: Partial<Record<SupportedHttpStatusCodes, string | string[]>>
```suggestion
  messages: Partial<Record<SupportedHttpStatusCodes, string[]>>
```
It's not a big deal adding in an extra `[]` for a single item and then it's easier to add a second.

2022-11-04 15:49 UTC, polymath-eric commented on src/test-utils/service-mocks.ts
> +export class MockTrustedClaimIssuersService {
Prashant added this package recently: https://www.npmjs.com/package/@golevelup/ts-jest

You should be able to do `createMock<MockTrustedClaimIssuersService>()` where ever you need this instead.

You might want to define a Nest `Provder` object in this file to save on test boiler plate.

2022-11-04 18:57 UTC, polymath-eric commented on src/common/decorators/swagger.ts
> +  messages: Partial<Record<SupportedHttpStatusCodes, string | string[]>>
`Arrary.isArrary` -> `rawDescription.length > 1` ?

I won't block approval on this though, either way is OK

2022-11-04 18:58 UTC, polymath-eric commented on src/common/decorators/swagger.ts
> +      ? '<ul>' + rawDescription.map(v => `<li>${v}</li>`).join(' ') + '</ul>'
(style) Usually we don't do single letter variables, even if they are close to the definition.
```suggestion
      ? '<ul>' + rawDescription.map(description => `<li>${description}</li>`).join(' ') + '</ul>'
```

I still find myself doing single letters for things like this from time to time though.

2022-11-07 10:01 UTC, prashantasdeveloper requested changes
While your at it, the `trustedFor` in `TrustedClaimIssuerDto` needs to be amended to support `null`. Can you take care of that as well?

2022-11-09 14:18 UTC, polymath-eric commented on src/compliance/trusted-claim-issuers.controller.spec.ts
> +      // @ts-ignore
why ts ignore?

2022-11-09 20:36 UTC, polymath-eric commented on src/compliance/dto/trusted-claim-issuer.dto.ts
> +  readonly trustedFor?: ClaimType[] | null;
```suggestion
  readonly trustedFor: ClaimType[] | null = null;
```
If this gets defaulted to null, then we don't have to deal with the undefined case, which means a type assertion isn't needed in the service.

2022-11-09 20:36 UTC, polymath-eric commented on src/compliance/dto/trusted-claim-issuer.dto.ts
> +    nullable: true,
```suggestion
    nullable: true,
    default: null
```

2022-11-09 20:36 UTC, polymath-eric commented on src/compliance/trusted-claim-issuers.service.ts
> +      rest as ModifyAssetTrustedClaimIssuersAddSetParams,
```suggestion
      rest,
```
If the DTO matches the signature there is no need to assert this.

The SDK is checking explicitly for null in a function, so this assertion is unsound.

`(aTrustedFor === null && bTrustedFor === null)`
https://github.com/PolymathNetwork/polymesh-sdk/blob/339b750301f99ccff0c390a00fdbf1f153765999/src/api/procedures/modifyAssetTrustedClaimIssuers.ts#L84

2022-11-09 20:36 UTC, polymath-eric commented on src/test-utils/mocks.ts
> +  transactions: TransactionResult<any>['transactions'];
```suggestion
  transactions: TransactionResult<T>['transactions'];
```
?

2022-11-10 17:27 UTC, polymath-eric approved these changes
LGTM

2022-11-11 09:32 UTC, prashantasdeveloper approved these changes

2022-11-11 09:58 UTC, merged

2022-11-11 10:03 UTC, polymath-eric commented
:tada: This PR is included in version 2.1.0 :tada:

The release is available on [GitHub release](https://github.com/PolymeshAssociation/polymesh-rest-api/releases/tag/v2.1.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: