feat: 🎸 get treasury account
PolymeshAssociation/polymesh-rest-api pull request #140
Opened 2022-11-12 15:10 UTC by sansan

### JIRA Link 

https://polymesh.atlassian.net/browse/DA-64

### Changelog / Description 

adds `GET /accounts/treasury` method to retrieve treasury account information

### Checklist - 

- [x] New Feature ?
- [x] Updated swagger annotation (if API structure is changed) ?
- [x] Unit Test (if possible) ?
- [x] Updated the Readme.md (if required) ?

2022-11-14 12:08 UTC, prashantasdeveloper requested changes

2022-11-14 12:08 UTC, prashantasdeveloper commented on src/accounts/accounts.controller.ts
> +  }
```suggestion
    const { address } = this.networkService.getTreasuryAccount();

    return new AccountModel({ address });
  }
```

2022-11-14 12:08 UTC, prashantasdeveloper commented on src/accounts/accounts.module.ts
> +  providers: [AccountsService, NetworkService],
You should import here NetworkModule instead of providing service again

2022-11-14 12:08 UTC, prashantasdeveloper commented on src/network/network.service.spec.ts
> +    it('should latest block ID', async () => {
```suggestion
    it('should return the chain's treasury Account', async () => {
```

2022-11-14 12:08 UTC, prashantasdeveloper commented on src/network/network.service.spec.ts
> +      const result = await networkService.getTreasuryAccount();
```suggestion
      const result = networkService.getTreasuryAccount();
```

2022-11-14 12:10 UTC, prashantasdeveloper commented
@polymath-eric shouldn't this get merged in alpha instead of master?

2022-11-14 18:16 UTC, polymath-eric reviewed
LGTM.

I think the PR should go into alpha for now though so we can releases a bit more bundled.

2022-11-14 18:16 UTC, polymath-eric commented on src/accounts/accounts.controller.ts
> +    description: 'This endpoint retrieves treasury Account details',
```suggestion
    description: 'This endpoint retrieves the treasury Account details',
```

I think its singular, otherwise use the plural form

2022-11-15 10:29 UTC, prashantasdeveloper commented
> though - the alpha branch should be updated first - otherwise there is a huge list of changes that are in master but are not in alpha?

https://github.com/PolymeshAssociation/polymesh-rest-api/pull/143 I have created a PR for the same

2022-11-21 20:55 UTC, polymath-eric commented on src/test-utils/mocks.ts
> +export const testAccount = createMock<Account>({ address: 'address' });
I think I won the merge race.

Can you move this to the const files for consistency?

2022-11-21 20:58 UTC, polymath-eric approved these changes
LGTM.

I think that testAccount can be moved into consts, but if its awkward since its a mock than maybe it should stay where it is.

2022-11-24 11:09 UTC, prashantasdeveloper approved these changes

2022-11-24 11:11 UTC, merged

2022-11-24 11:16 UTC, polymath-eric commented
:tada: This PR is included in version 2.2.0-alpha.1 :tada:

The release is available on [GitHub release](https://github.com/PolymeshAssociation/polymesh-rest-api/releases/tag/v2.2.0-alpha.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-12-06 15:17 UTC, polymath-eric commented
:tada: This PR is included in version 2.3.0 :tada:

The release is available on [GitHub release](https://github.com/PolymeshAssociation/polymesh-rest-api/releases/tag/v2.3.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: