feat: 🎸 check if compliance requirements are paused
PolymeshAssociation/polymesh-rest-api pull request #141
Opened 2022-11-14 12:53 UTC by sansan

### JIRA Link 

https://polymesh.atlassian.net/browse/DA-64

### Changelog / Description 

adds endpoint for checking if compliacne requirements are paused for an Asset

### Checklist - 

- [x] New Feature ?
- [x] Updated swagger annotation (if API structure is changed) ?
- [x] Unit Test (if possible) ?
- [x] Updated the Readme.md (if required) ?

2022-11-14 13:12 UTC, prashantasdeveloper requested changes

2022-11-14 13:12 UTC, prashantasdeveloper commented on src/compliance/compliance-requirements.controller.ts
> +    description: 'This endpoint checks if the requirements are paused',
```suggestion
    description: 'This endpoint checks if the compliance requirements are paused for a given ticker',
```

2022-11-14 13:12 UTC, prashantasdeveloper commented on src/compliance/compliance-requirements.controller.ts
> +    return result;
```suggestion
    return this.complianceRequirementsService.arePaused(ticker);
```

2022-11-14 13:12 UTC, prashantasdeveloper commented on src/compliance/compliance-requirements.service.spec.ts
> +    it('should return ', async () => {
```suggestion
    it('should return the Asset compliance requirement state ', async () => {
```

2022-11-14 13:12 UTC, prashantasdeveloper commented on src/compliance/compliance-requirements.controller.ts
> +  @Post('are-paused')
```suggestion
  @Get('are-paused')
```

2022-11-14 19:08 UTC, polymath-eric requested changes
Code looks good.

I think the route should be a noun since it is a GET and we should return a model to help with documentation and make it extensible.

2022-11-14 19:08 UTC, polymath-eric commented on src/compliance/compliance-requirements.controller.ts
> +  @Get('are-paused')
I'd say something like:
```suggestion
  @Get('/status')
```
and make the return an object with a key.

Generally we want to routes to be REST like, with the exception being for actions.

2022-11-14 19:08 UTC, polymath-eric commented on src/compliance/compliance-requirements.controller.ts
> +  public async areRequirementsPaused(@Param() { ticker }: TickerParamsDto): Promise<boolean> {
```suggestion
  public async areRequirementsPaused(@Param() { ticker }: TickerParamsDto): Promise<ComplianceStatusModel> {
```
and declare it as a model.

Keep the scope to only being pause or not for now, but allow it to be extended and a bit more generic.

2022-11-14 19:08 UTC, polymath-eric commented on src/compliance/mocks/compliance-requirements.mock.ts
> +              value: 'Ox6'.padEnd(66, '0'),
(note) if my consts PR gets merged, update these.

If this gets merged in first I will update in that PR.

2022-11-23 14:51 UTC, polymath-eric approved these changes

2022-11-24 11:21 UTC, prashantasdeveloper requested changes

2022-11-24 11:21 UTC, prashantasdeveloper commented on src/compliance/models/compliance-status.model.ts
> +  readonly arePaused: boolean;
```suggestion
  @ApiProperty({
    description: 'Indicator to know if compliance requirements are paused or not',
    type: 'boolean',
    example: true,
  })
  readonly paused: boolean;
```

2022-11-24 11:21 UTC, prashantasdeveloper commented on src/compliance/models/compliance-status.model.ts
> +  readonly arePaused: boolean;
`@FromBigNumber` is only needed when return type is BigNumber. Feels like it got copied over

2022-11-24 11:21 UTC, prashantasdeveloper commented on src/compliance/compliance-requirements.service.spec.ts
> +    it('should return ', async () => {
This was not updated

2022-11-25 12:08 UTC, prashantasdeveloper approved these changes

2022-11-25 12:09 UTC, merged

2022-11-25 12:13 UTC, polymath-eric commented
:tada: This PR is included in version 2.2.0-alpha.2 :tada:

The release is available on [GitHub release](https://github.com/PolymeshAssociation/polymesh-rest-api/releases/tag/v2.2.0-alpha.2)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-12-06 15:17 UTC, polymath-eric commented
:tada: This PR is included in version 2.3.0 :tada:

The release is available on [GitHub release](https://github.com/PolymeshAssociation/polymesh-rest-api/releases/tag/v2.3.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: