feat: 🎸 add dev testing endpoint to aid with integration tests
PolymeshAssociation/polymesh-rest-api pull request #158
Opened 2023-01-04 21:51 UTC by polymath-eric

### JIRA Link 

[DA-473](https://polymesh.atlassian.net/browse/DA-473)

### Changelog / Description 

adds `/developer-testing/create-admins` and
`/developer-testing/create-identity-batch` to allow for account setup during integration type tests

### Checklist - 

- [ ] New Feature ?
- [ ] Updated swagger annotation (if API structure is changed) ?
- [ ] Unit Test (if possible) ?
- [ ] Updated the Readme.md (if required) ?

2023-01-04 21:52 UTC, polymath-eric commented
Draft so the SDK beta into alpha can get merged (we need beta for subsidies, but alpha to clean up the `setSigner` call)

2023-01-06 10:42 UTC, prashantasdeveloper requested changes
Left some nit comments, but overall LGTM

2023-01-06 10:42 UTC, prashantasdeveloper commented on src/developer-testing/developer-testing.controller.ts
> +  }
@ApiResponse is missing here.

2023-01-06 10:42 UTC, prashantasdeveloper commented on src/developer-testing/developer-testing.controller.ts
> +  }
Also, just to be consistent I would recommend changing the return type to `Promise<ResultsModel<IdentityModel>>`. Can leave as it as well

2023-01-06 10:42 UTC, prashantasdeveloper commented on src/developer-testing/developer-testing.controller.ts
> +  }
@ApiResponse is missing here as well

2023-01-06 10:42 UTC, prashantasdeveloper commented on src/developer-testing/developer-testing.service.ts
> +      this._alicePair = keyring.addFromUri('//Alice');
IMO we should add an extra variable in environments and default it to '//Alice'. That way if anyone wants to use this setup differently they don't have to edit the files

2023-01-06 10:42 UTC, prashantasdeveloper commented on src/developer-testing/dto/create-admin.dto.ts
> +export class CreateCddProviders {
nit -> Add Dto to the class name and make sure the class name and file name are in sync :)

2023-01-06 10:42 UTC, prashantasdeveloper commented on src/developer-testing/developer-testing.service.ts
> +/* istanbul ignore file */
Why are we ignoring the testing for this file? Atleast we should create a task to put in the tests later if we want this urgently. Not sure if I'm missing something here

2023-01-06 10:42 UTC, prashantasdeveloper commented on src/developer-testing/developer-testing.service.ts
> +const initialAdminPolyx = 100000000 * unitsPerPolyx;
nit -> if we can provide an option to take the amount as input that will be really helpful. We can default to this value

2023-01-06 10:42 UTC, prashantasdeveloper commented on src/developer-testing/dto/create-admin.dto.ts
> +
nit-> We can add in amount / balance attribute to specify the initial POLYX to be transferred to each Identity. And can default it to the value used in service

2023-01-07 03:12 UTC, polymath-eric commented on package.json
> +    "dedupe": "npx yarn-deduplicate yarn.lock",
Updating the SDK introduced the warning message that happen all the time.

According to some SO post, yarn 2 is more aggressive in dedupe and will likely eliminate them for us.

For now, this package does the dedupe, but lets us stay on yarn 1 for now.

It only needs to be ran when you see the warnings after updating something touching polkadot dependencies.

2023-01-09 14:47 UTC, polymath-eric commented
@prashantasdeveloper I refactored the old mock cdd endpoint to use the DeveloperTestingService.

I marked it as deprecated, since the batch call is better. I made that default to the sudo signer so its easier to migrate over, since that should be `//Alice`.

2023-01-09 14:59 UTC, prashantasdeveloper approved these changes
LGTM

2023-01-09 15:06 UTC, merged

2023-01-09 15:10 UTC, polymath-eric commented
:tada: This PR is included in version 2.5.0-alpha.1 :tada:

The release is available on [GitHub release](https://github.com/PolymeshAssociation/polymesh-rest-api/releases/tag/v2.5.0-alpha.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-02-08 16:10 UTC, polymath-eric commented
:tada: This PR is included in version 2.5.0 :tada:

The release is available on [GitHub release](https://github.com/PolymeshAssociation/polymesh-rest-api/releases/tag/v2.5.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: