feat: 🎸 withdraw affirmation for an instruction
PolymeshAssociation/polymesh-rest-api pull request #165
Opened 2023-01-10 15:46 UTC by sansan

### JIRA Link 

https://polymesh.atlassian.net/browse/DA-72

### Changelog / Description 

- adds an endpoint to withdraw an affirmation for an isntruction

### Checklist - 

- [x] New Feature ?
- [x] Updated swagger annotation (if API structure is changed) ?
- [x] Unit Test (if possible) ?
- [x] Updated the Readme.md (if required) ?

2023-01-17 14:51 UTC, prashantasdeveloper requested changes

2023-01-17 14:51 UTC, prashantasdeveloper commented on src/settlements/settlements.controller.ts
> +  })
Add ApiNotFoundResponse as well for the case where no instruction is found for given ID

2023-01-19 11:34 UTC, prashantasdeveloper approved these changes

2023-01-21 00:15 UTC, polymath-eric commented on src/settlements/settlements.service.spec.ts
> +    it('should run a withdraw affirmation procedure and return the queue data', async () => {
line shouldn't be changed

2023-01-30 21:24 UTC, polymath-eric approved these changes

2023-01-31 14:01 UTC, merged

2023-01-31 14:04 UTC, polymath-eric commented
:tada: This PR is included in version 2.5.0-alpha.3.9 :tada:

The release is available on [GitHub release](https://github.com/PolymeshAssociation/polymesh-rest-api/releases/tag/v2.5.0-alpha.3.9)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-02-08 16:09 UTC, polymath-eric commented
:tada: This PR is included in version 2.5.0 :tada:

The release is available on [GitHub release](https://github.com/PolymeshAssociation/polymesh-rest-api/releases/tag/v2.5.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: