feat: 🎸 quit portfolio custody
PolymeshAssociation/polymesh-rest-api pull request #172
Opened 2023-01-20 18:19 UTC by sansan

### JIRA Link 

https://polymesh.atlassian.net/browse/DA-78

### Changelog / Description 

- adds endpoint to quit custody over portfolio

### Checklist - 

- [x] New Feature ?
- [x] Updated swagger annotation (if API structure is changed) ?
- [x] Unit Test (if possible) ?
- [x] Updated the Readme.md (if required) ?

2023-01-20 18:41 UTC, polymath-eric approved these changes

2023-01-20 18:41 UTC, polymath-eric commented on src/portfolios/portfolios.controller.ts
> +    description: 'The ID of the portfolio for which to quit Custody. Use 0 for default Portfolio',
```suggestion
    description: 'The ID of the portfolio for which to quit Custody. Use 0 for the default Portfolio',
```

(nit)

2023-01-23 22:01 UTC, polymath-eric commented
SDK could be upgraded to `v19.0.0-alpha.14` to include the bug fix in quit custody

2023-01-31 13:47 UTC, VictorVicente requested changes
@sansan Could you update SDK to latest `beta` in this PR?

2023-01-31 20:27 UTC, polymath-eric approved these changes

2023-02-01 12:50 UTC, VictorVicente approved these changes

2023-02-01 12:50 UTC, merged

2023-02-01 12:54 UTC, polymath-eric commented
:tada: This PR is included in version 2.5.0-alpha.3.10 :tada:

The release is available on [GitHub release](https://github.com/PolymeshAssociation/polymesh-rest-api/releases/tag/v2.5.0-alpha.3.10)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-02-08 16:09 UTC, polymath-eric commented
:tada: This PR is included in version 2.5.0 :tada:

The release is available on [GitHub release](https://github.com/PolymeshAssociation/polymesh-rest-api/releases/tag/v2.5.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: