feat: 🎸 Add API Key Swagger support
PolymeshAssociation/polymesh-rest-api pull request #175
Opened 2023-02-07 14:25 UTC by prashantasdeveloper

### JIRA Link 

DA-445

### Changelog / Description 

This allows swagger to enable apiKey authorization if `AUTH_STRATEGY` is set as `apiKey`
<img width="1486" alt="Screenshot 2023-02-07 at 7 53 33 PM" src="https://user-images.githubusercontent.com/34747455/217271167-38c35551-e08c-4c79-8862-2f534f42545f.png">

### Checklist - 

- [x] New Feature ?
- [ ] Updated swagger annotation (if API structure is changed) ?
- [ ] Unit Test (if possible) ?
- [ ] Updated the Readme.md (if required) ?

2023-02-07 16:20 UTC, polymath-eric approved these changes
Looks good. I like the swagger experience with this.

2023-02-07 16:31 UTC, polymath-eric commented on src/main.ts
> +  const authStrategies = parseAuthStrategyConfig(process.env.AUTH_STRATEGY || '');
I thought of this now:

I think you can use a method like `app.get<ConfigService>(ConfigService)` and use that as if it was injected.

We use the syntax in tests. I think it slightly cleaner than reading `env` here directly and should be more consistent.

2023-02-07 16:37 UTC, polymath-eric requested changes
small nitty change, but I think it will prevent the chance of docs and implementation from getting desynced.

2023-02-07 16:37 UTC, polymath-eric commented on src/auth/auth.utils.ts
> +export const parseAuthStrategyConfig = (rawStrategyConfig: string): AuthStrategy[] => {
```suggestion
 const parseAuthStrategyConfig = (rawStrategyConfig: string): AuthStrategy[] => {
```

2023-02-08 13:14 UTC, prashantasdeveloper commented on src/auth/auth.utils.ts
> +export const parseAuthStrategyConfig = (rawStrategyConfig: string): AuthStrategy[] => {
I still need this to parse the values defined in env file

2023-02-08 13:27 UTC, polymath-eric commented on src/auth/auth.utils.ts
> +export const parseAuthStrategyConfig = (rawStrategyConfig: string): AuthStrategy[] => {
You can read the already parsed value from the config service.

2023-02-08 13:30 UTC, polymath-eric commented on src/auth/auth.utils.ts
> +export const parseAuthStrategyConfig = (rawStrategyConfig: string): AuthStrategy[] => {
Oh, sorry you are right.

2023-02-08 13:30 UTC, polymath-eric approved these changes

2023-02-08 13:51 UTC, merged

2023-02-08 13:56 UTC, polymath-eric commented
:tada: This PR is included in version 2.5.0-alpha.3.13 :tada:

The release is available on [GitHub release](https://github.com/PolymeshAssociation/polymesh-rest-api/releases/tag/v2.5.0-alpha.3.13)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-02-08 16:09 UTC, polymath-eric commented
:tada: This PR is included in version 2.5.0 :tada:

The release is available on [GitHub release](https://github.com/PolymeshAssociation/polymesh-rest-api/releases/tag/v2.5.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: