feat: 🎸 add/remove agent to a PermissionGroup
PolymeshAssociation/polymesh-rest-api pull request #312
Opened 2024-11-27 23:22 UTC by sansan

### JIRA Link 

https://polymesh.atlassian.net/browse/DA-94
https://polymesh.atlassian.net/browse/DA-95

### Changelog / Description 

- adds endpoint to list grous for asset (with permissions assigned to the group)
- adds endpoint to add an agent to a group (group can be passed as id, known group type or permissions)
- adds endpoint to remove external agent

### Checklist - 

- [x] New Feature ?
- [x] Updated swagger annotation (if API structure is changed) ?
- [x] Unit Test (if possible) ?

2024-11-28 00:36 UTC, polymath-eric commented on src/assets/models/permission-group-with-permissions.model.ts
> +  @ApiPropertyOptional({
Shouldn't the model always have an ID? Why is this optional?

2024-11-28 00:36 UTC, polymath-eric commented on src/assets/models/permission-group-with-permissions.model.ts
> +    format: 'bigint',
`example` ?

I think enum and type might not need them specified

2024-11-28 05:48 UTC, prashantasdeveloper requested changes
I think we should have separate permission-group module, controller, service so that we would not overstuff asset classes.

2024-11-28 05:48 UTC, prashantasdeveloper commented on src/assets/dto/invite-agent-to-group.dto.ts
> +    description: 'The did of the target identity to invite to the group',
```suggestion
    description: 'The DID of the target identity to invite to the group',
```

2024-11-28 05:48 UTC, prashantasdeveloper commented on src/assets/dto/remove-agent-from-grop.dto.ts
> +import { OmitType } from '@nestjs/swagger';
istanbul ignore

2024-11-28 05:48 UTC, prashantasdeveloper commented on src/assets/models/group-permissions.model.ts
> +      'Transaction Groups that the Account can execute. Having permissions over a [TxGroup](https://github.com/polymeshassociation/polymesh-sdk/blob/docs/v14/docs/enums/txgroup.md) means having permi
the url gives 404

2024-11-28 05:48 UTC, prashantasdeveloper commented on src/assets/models/permission-group-with-permissions.model.ts
> +  })
@IsOptional and @IsEnum missing

2024-11-28 05:48 UTC, prashantasdeveloper commented on src/assets/assets.controller.ts
> +  @Post(':asset/permission-groups/create')
If the endpoint is renamed, this should be marked as breaking change

2024-11-28 05:48 UTC, prashantasdeveloper commented on src/assets/assets.controller.ts
> +    return handleServiceResult(result);
All these APIs should be moved in its own controller - PermissionGroupController with endpoint as :asset/permission-groups

2024-12-06 17:19 UTC, polymath-eric approved these changes

2024-12-06 18:29 UTC, merged